### ISSUE TITLE
Las imagenes de PayPal usan recursos con certificados inseguros

### ISSUE THREAD

**Issue by lhchavez** [omegaup/nonprofit-web#11]
Chromium dixit:

> The SSL certificate used to load resources from https://www.paypalobjects.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by samdsmx** [comment]
@lhchavez  Es relevante esto aun?

**Comment by lhchavez** [comment]
checa a ver si chrome muestra errores/advertencias de seguridad.

**Comment by samdsmx** [comment]
ningun error. la consola esta limpia
