### ISSUE TITLE
No funciona el botón "CONTACT US" y tampoco hay documentación de los términos y privacidad en https://www.omegaup.org/

### ISSUE THREAD

**Issue by tvanessa** [omegaup/nonprofit-web#75]
FROM: [omegaup/6905](https://github.com/omegaup/omegaup/issues/6905)

No funciona el botón "CONTACT US" y tampoco hay documentación de los términos y privacidad en https://www.omegaup.org/

Quise contactame con ustedes a través de su página web y hice click en el botón "Contact us" y también quise ver los términos y privacidad. 

## Comportamiento Actual

**Quise hacer click en el botón "Contact us", pero no hace nada, parece que no tiene funcionalidad alguna. Además, los términos y provacidad tampoco lleva a un link, donse se muestren la información del proveedor y términos y políticas aplicables.**

## Posible Solución

En la etiqueta <a> del  "Contact us" del archivo html, se puede colocar un mensaje ya automatizado para hacer llegar su consulta o mensaje.

Ejemplo: <a class="Contactus__link" href="mailto:sebastian.arana2016@gmail.com?subject=Consulta" 

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): edge
* Sistema Operativo y versión (escritorio o móvil): windows 11
* Link al sitio en el que este problema pasa: https://www.omegaup.org/
* Captura de pantalla:

**Comment by samdsmx** [comment]
Done.
